<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="an-test" name="com.bluemeric.test.GenerateTest" tests="8" failures="0" timestamp="26 Oct 2016 09:31:21 GMT" time="4.013" errors="7">
  <testcase name="getTest" time="0.335" classname="com.bluemeric.test.GenerateTest"/>
  <testcase name="getTest" time="0.491" classname="com.bluemeric.test.GenerateTest">
    <error type="java.lang.AssertionError" message="Expected response code is 200. But got 404. Hence failed the test.">
      <![CDATA[java.lang.AssertionError: Expected response code is 200. But got 404. Hence failed the test.
	at org.testng.Assert.fail(Assert.java:89)
	at com.bluemeric.test.GenerateTest.getTest(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at com.bluemeric.test.RunTest.runTests(Unknown Source)
	at com.bluemeric.test.RunTest.main(Unknown Source)
]]>
    </error>
  </testcase> <!-- getTest -->
  <testcase name="getTest" time="0.353" classname="com.bluemeric.test.GenerateTest">
    <error type="java.lang.AssertionError" message="Expected response code is 200. But got 404. Hence failed the test.">
      <![CDATA[java.lang.AssertionError: Expected response code is 200. But got 404. Hence failed the test.
	at org.testng.Assert.fail(Assert.java:89)
	at com.bluemeric.test.GenerateTest.getTest(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at com.bluemeric.test.RunTest.runTests(Unknown Source)
	at com.bluemeric.test.RunTest.main(Unknown Source)
]]>
    </error>
  </testcase> <!-- getTest -->
  <testcase name="getTest" time="1.373" classname="com.bluemeric.test.GenerateTest">
    <error type="java.lang.AssertionError" message="Expected response is Instances currently registered with Eureka. But received reponse = &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot; &quot;http://www.w3.org/TR/html4/loose.dtd&quot;&gt;
&lt;html&gt;
&lt;head&gt;
&lt;base href=&quot;/hystrix&quot;&gt;
&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=ISO-8859-1&quot;&gt;
&lt;title&gt;Hystrix Dashboard&lt;/title&gt;

	&lt;!-- Javascript to monitor and display --&gt;
	&lt;script src=&quot;/webjars/jquery/2.1.1/jquery.min.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
	
	&lt;script&gt;
		function sendToMonitor() {
			
			if($(&#039;#stream&#039;).val().length &gt; 0) {
				var url = &quot;/hystrix/monitor?stream=&quot; + encodeURIComponent($(&#039;#stream&#039;).val()) + &quot;&quot;;
				if($(&#039;#delay&#039;).val().length &gt; 0) {	
					url += &quot;&amp;delay=&quot; + $(&#039;#delay&#039;).val();
				}
				if($(&#039;#title&#039;).val().length &gt; 0) {	
					url += &quot;&amp;title=&quot; + encodeURIComponent($(&#039;#title&#039;).val());
				}
				location.href= url;
			} else {
				$(&#039;#message&#039;).html(&quot;The &#039;stream&#039; value is required.&quot;);
			}
		}
	&lt;/script&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;div style=&quot;width:800px;margin:0 auto;&quot;&gt;
	
	&lt;center&gt;
	&lt;img width=&quot;264&quot; height=&quot;233&quot; src=&quot;/hystrix/images/hystrix-logo.png&quot;&gt;
	&lt;br&gt;
	&lt;br&gt;
	
	&lt;h2&gt;Hystrix Dashboard&lt;/h2&gt;
	&lt;input id=&quot;stream&quot; type=&quot;textfield&quot; size=&quot;120&quot; placeholder=&quot;http://hostname:port/turbine/turbine.stream&quot;&gt;&lt;/input&gt;
	&lt;br&gt;&lt;br&gt;
	&lt;i&gt;Cluster via Turbine (default cluster):&lt;/i&gt; http://turbine-hostname:port/turbine.stream
	&lt;br&gt;
	&lt;i&gt;Cluster via Turbine (custom cluster):&lt;/i&gt; http://turbine-hostname:port/turbine.stream?cluster=[clusterName]
	&lt;br&gt;
	&lt;i&gt;Single Hystrix App:&lt;/i&gt; http://hystrix-app:port/hystrix.stream
	&lt;br&gt;&lt;br&gt;
	Delay: &lt;input id=&quot;delay&quot; type=&quot;textfield&quot; size=&quot;10&quot; placeholder=&quot;2000&quot;&gt;&lt;/input&gt;ms 
	&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp; 
	Title: &lt;input id=&quot;title&quot; type=&quot;textfield&quot; size=&quot;60&quot; placeholder=&quot;Example Hystrix App&quot;&gt;&lt;/input&gt;&lt;br&gt;
	&lt;br&gt;
	&lt;button onclick=&quot;sendToMonitor()&quot;&gt;Monitor Stream&lt;/button&gt;
	&lt;br&gt;&lt;br&gt;
	&lt;div id=&quot;message&quot; style=&quot;color:red&quot;&gt;&lt;/div&gt;
	
	&lt;/center&gt;
&lt;/div&gt;
&lt;/body&gt;
&lt;/html&gt;. Output mismatching. Hence failing the test.">
      <![CDATA[java.lang.AssertionError: Expected response is Instances currently registered with Eureka. But received reponse = <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<base href="/hystrix">
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Hystrix Dashboard</title>

	<!-- Javascript to monitor and display -->
	<script src="/webjars/jquery/2.1.1/jquery.min.js" type="text/javascript"></script>
	
	<script>
		function sendToMonitor() {
			
			if($('#stream').val().length > 0) {
				var url = "/hystrix/monitor?stream=" + encodeURIComponent($('#stream').val()) + "";
				if($('#delay').val().length > 0) {	
					url += "&delay=" + $('#delay').val();
				}
				if($('#title').val().length > 0) {	
					url += "&title=" + encodeURIComponent($('#title').val());
				}
				location.href= url;
			} else {
				$('#message').html("The 'stream' value is required.");
			}
		}
	</script>
</head>
<body>
<div style="width:800px;margin:0 auto;">
	
	<center>
	<img width="264" height="233" src="/hystrix/images/hystrix-logo.png">
	<br>
	<br>
	
	<h2>Hystrix Dashboard</h2>
	<input id="stream" type="textfield" size="120" placeholder="http://hostname:port/turbine/turbine.stream"></input>
	<br><br>
	<i>Cluster via Turbine (default cluster):</i> http://turbine-hostname:port/turbine.stream
	<br>
	<i>Cluster via Turbine (custom cluster):</i> http://turbine-hostname:port/turbine.stream?cluster=[clusterName]
	<br>
	<i>Single Hystrix App:</i> http://hystrix-app:port/hystrix.stream
	<br><br>
	Delay: <input id="delay" type="textfield" size="10" placeholder="2000"></input>ms 
	&nbsp;&nbsp;&nbsp;&nbsp; 
	Title: <input id="title" type="textfield" size="60" placeholder="Example Hystrix App"></input><br>
	<br>
	<button onclick="sendToMonitor()">Monitor Stream</button>
	<br><br>
	<div id="message" style="color:red"></div>
	
	</center>
</div>
</body>
</html>. Output mismatching. Hence failing the test.
	at org.testng.Assert.fail(Assert.java:89)
	at com.bluemeric.test.GenerateTest.getTest(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at com.bluemeric.test.RunTest.runTests(Unknown Source)
	at com.bluemeric.test.RunTest.main(Unknown Source)
]]>
    </error>
  </testcase> <!-- getTest -->
  <testcase name="getTest" time="0.347" classname="com.bluemeric.test.GenerateTest">
    <error type="java.lang.AssertionError" message="Expected response code is 200. But got 404. Hence failed the test.">
      <![CDATA[java.lang.AssertionError: Expected response code is 200. But got 404. Hence failed the test.
	at org.testng.Assert.fail(Assert.java:89)
	at com.bluemeric.test.GenerateTest.getTest(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at com.bluemeric.test.RunTest.runTests(Unknown Source)
	at com.bluemeric.test.RunTest.main(Unknown Source)
]]>
    </error>
  </testcase> <!-- getTest -->
  <testcase name="getTest" time="0.348" classname="com.bluemeric.test.GenerateTest">
    <error type="java.lang.AssertionError" message="Expected response code is 200. But got 404. Hence failed the test.">
      <![CDATA[java.lang.AssertionError: Expected response code is 200. But got 404. Hence failed the test.
	at org.testng.Assert.fail(Assert.java:89)
	at com.bluemeric.test.GenerateTest.getTest(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at com.bluemeric.test.RunTest.runTests(Unknown Source)
	at com.bluemeric.test.RunTest.main(Unknown Source)
]]>
    </error>
  </testcase> <!-- getTest -->
  <testcase name="getTest" time="0.351" classname="com.bluemeric.test.GenerateTest">
    <error type="java.lang.AssertionError" message="Expected response code is 200. But got 404. Hence failed the test.">
      <![CDATA[java.lang.AssertionError: Expected response code is 200. But got 404. Hence failed the test.
	at org.testng.Assert.fail(Assert.java:89)
	at com.bluemeric.test.GenerateTest.getTest(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at com.bluemeric.test.RunTest.runTests(Unknown Source)
	at com.bluemeric.test.RunTest.main(Unknown Source)
]]>
    </error>
  </testcase> <!-- getTest -->
  <testcase name="getTest" time="0.415" classname="com.bluemeric.test.GenerateTest">
    <error type="java.lang.AssertionError" message="Expected response is localApplication. But received reponse = {&quot;status&quot;:&quot;UP&quot;,&quot;diskSpace&quot;:{&quot;status&quot;:&quot;UP&quot;,&quot;total&quot;:105654812672,&quot;free&quot;:98012565504,&quot;threshold&quot;:10485760},&quot;refreshScope&quot;:{&quot;status&quot;:&quot;UP&quot;},&quot;hystrix&quot;:{&quot;status&quot;:&quot;UP&quot;}}. Output mismatching. Hence failing the test.">
      <![CDATA[java.lang.AssertionError: Expected response is localApplication. But received reponse = {"status":"UP","diskSpace":{"status":"UP","total":105654812672,"free":98012565504,"threshold":10485760},"refreshScope":{"status":"UP"},"hystrix":{"status":"UP"}}. Output mismatching. Hence failing the test.
	at org.testng.Assert.fail(Assert.java:89)
	at com.bluemeric.test.GenerateTest.getTest(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:702)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:894)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1219)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:768)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1188)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1113)
	at org.testng.TestNG.run(TestNG.java:1025)
	at com.bluemeric.test.RunTest.runTests(Unknown Source)
	at com.bluemeric.test.RunTest.main(Unknown Source)
]]>
    </error>
  </testcase> <!-- getTest -->
</testsuite> <!-- com.bluemeric.test.GenerateTest -->
