<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="an-test" name="GET-Eureka2-health" tests="1" failures="1" timestamp="26 Oct 2016 09:31:19 GMT" time="0.417" errors="0">
  <testcase name="getTest" time="0.415" classname="com.bluemeric.test.GenerateTest">
    <failure type="java.lang.AssertionError" message="Expected response is localApplication. But received reponse = {&amp;quot;status&amp;quot;:&amp;quot;UP&amp;quot;,&amp;quot;diskSpace&amp;quot;:{&amp;quot;status&amp;quot;:&amp;quot;UP&amp;quot;,&amp;quot;total&amp;quot;:105654812672,&amp;quot;free&amp;quot;:98012565504,&amp;quot;threshold&amp;quot;:10485760},&amp;quot;refreshScope&amp;quot;:{&amp;quot;status&amp;quot;:&amp;quot;UP&amp;quot;},&amp;quot;hystrix&amp;quot;:{&amp;quot;status&amp;quot;:&amp;quot;UP&amp;quot;}}. Output mismatching. Hence failing the test.">
      <![CDATA[java.lang.AssertionError: Expected response is localApplication. But received reponse = {"status":"UP","diskSpace":{"status":"UP","total":105654812672,"free":98012565504,"threshold":10485760},"refreshScope":{"status":"UP"},"hystrix":{"status":"UP"}}. Output mismatching. Hence failing the test.
	at com.bluemeric.test.GenerateTest.getTest(Unknown Source)
	at com.bluemeric.test.RunTest.runTests(Unknown Source)
	at com.bluemeric.test.RunTest.main(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- getTest -->
</testsuite> <!-- GET-Eureka2-health -->
